name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    environment: release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          node-version: '20'
          platform: ${{ matrix.platform }}

      - name: Generate Release Notes
        id: notes
        uses: ./.github/actions/generate-release-notes

      - name: Build Tauri Application
        id: tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          VITE_SERVER_URL: ${{ vars.VITE_SERVER_URL }}
        with:
          projectPath: app
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseBody: ${{ steps.notes.outputs.release_body }}
          releaseDraft: true
          prerelease: false

